### ISSUE TITLE
Utilize and prioritize prepared Stampy answers

### ISSUE THREAD

**Issue by cvarrichio** [StampyAI/stampy-chat#11] opened 2023-05-06 19:53 UTC
Up to date Stampy answers should be prioritized in responses with as little modification as possible.

**Comment by ccstan99** [comment] 2023-06-17 09:34
From McGill Team's plan

**Privilege curated sources in search:**
add biases to good/bad sources to make them more/less easily found by semantic search. Random personal blogs on lesswrong---,  stampy+++, highly upvoted stuff ++, etc. Extending the length of good vectors by 0.1, and decreasing the length of bad vectors by 0.1, might work for this while still permitting search for ‘bad’ sources.

**Comment by ccstan99** [comment] 2023-07-17 03:55
Duplicate of #64

**Closed** 2023-07-17 03:56 UTC
Labels: enhancement
